Import basic libraries

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

Create input and output records

In [6]:
# AND gate truth table
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [0], [0], [1]])

# Create a sequential model

In [8]:
model=Sequential()

# Add a dense layer with one neuron and sigmoid activation function

In [9]:
model.add(Dense(units=1, input_dim=2, activation='sigmoid'))

# Compile the model

In [10]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

# Train the model

verbose=0: No output will be displayed during the training process.
verbose=1: Displays a progress bar for each epoch, showing the training progress.
verbose=2: Displays one line per epoch, providing a summary of the training progress.

In [20]:
model.fit(X, Y, epochs=1000, verbose=2)

Epoch 1/1000
1/1 - 0s - loss: 0.2300 - accuracy: 0.7500 - 13ms/epoch - 13ms/step
Epoch 2/1000
1/1 - 0s - loss: 0.2299 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 3/1000
1/1 - 0s - loss: 0.2297 - accuracy: 0.7500 - 12ms/epoch - 12ms/step
Epoch 4/1000
1/1 - 0s - loss: 0.2296 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 5/1000
1/1 - 0s - loss: 0.2294 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 6/1000
1/1 - 0s - loss: 0.2293 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 7/1000
1/1 - 0s - loss: 0.2291 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 8/1000
1/1 - 0s - loss: 0.2290 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 9/1000
1/1 - 0s - loss: 0.2288 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 10/1000
1/1 - 0s - loss: 0.2287 - accuracy: 0.7500 - 9ms/epoch - 9ms/step
Epoch 11/1000
1/1 - 0s - loss: 0.2285 - accuracy: 0.7500 - 16ms/epoch - 16ms/step
Epoch 12/1000
1/1 - 0s - loss: 0.2284 - accuracy: 0.7500 - 10ms/epoch - 10ms/step
Epoch 13/1000
1/1 - 0s - loss: 0.

# Test the model

In [12]:
print("Predictions:")
print(model.predict(X))

Predictions:
1/1 [==============================] - 1s 776ms/step
[[0.47528687]
 [0.7476278 ]
 [0.50093246]
 [0.7665019 ]]


In [16]:
print("Predictions:")
print(model.predict(X))

Predictions:
1/1 [==============================] - 0s 43ms/step
[[0.42734814]
 [0.66894734]
 [0.41801548]
 [0.66042334]]


# Evaluate the model

In [17]:
loss, accuracy = model.evaluate(X, Y)
print(f"Loss: {loss:.4f}, Accuracy: {accuracy * 100:.2f}%")

1/1 [==============================] - 0s 347ms/step - loss: 0.2300 - accuracy: 0.7500
Loss: 0.2300, Accuracy: 75.00%


# Test the model

In [21]:
print("Predictions:")
predictions = model.predict(X)
threshold = 0.5
binary_predictions = np.where(predictions >= threshold, 1, 0)
print(binary_predictions)

Predictions:
1/1 [==============================] - 0s 24ms/step
[[0]
 [0]
 [0]
 [1]]


# Evaluate the model

In [19]:
loss, accuracy = model.evaluate(X, Y)
print(f"Loss: {loss:.4f}, Accuracy: {accuracy * 100:.2f}%")

1/1 [==============================] - 0s 45ms/step - loss: 0.2300 - accuracy: 0.7500
Loss: 0.2300, Accuracy: 75.00%


XOR table

In [22]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# XOR gate truth table
data = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])

labels = np.array([0, 1, 1, 0])

In [23]:
# Create a sequential neural network model
model = Sequential()

# Add a hidden layer with 2 neurons and input layer with 2 neurons
model.add(Dense(2, input_dim=2, activation='sigmoid'))

In [24]:
# Add an output layer with 1 neuron
model.add(Dense(1, activation='sigmoid'))

In [25]:
# Compile the model
sgd = SGD(learning_rate=0.1)
model.compile(loss='mean_squared_error', optimizer=sgd)

In [27]:
# Train the model
epochs = 100
model.fit(data, labels, epochs=epochs, verbose=1)

Epoch 1/100
1/1 [==============================] - 0s 19ms/step - loss: 0.2499
Epoch 2/100
1/1 [==============================] - 0s 16ms/step - loss: 0.2499
Epoch 3/100
1/1 [==============================] - 0s 16ms/step - loss: 0.2499
Epoch 4/100
1/1 [==============================] - 0s 16ms/step - loss: 0.2499
Epoch 5/100
1/1 [==============================] - 0s 15ms/step - loss: 0.2499
Epoch 6/100
1/1 [==============================] - 0s 16ms/step - loss: 0.2499
Epoch 7/100
1/1 [==============================] - 0s 20ms/step - loss: 0.2499
Epoch 8/100
1/1 [==============================] - 0s 15ms/step - loss: 0.2499
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 0.2499
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 0.2499
Epoch 11/100
1/1 [==============================] - 0s 13ms/step - loss: 0.2499
Epoch 12/100
1/1 [==============================] - 0s 14ms/step - loss: 0.2499
Epoch 13/100
1/1 [==============================]

In [28]:
# Evaluate the model
print("Training completed. Evaluating the model...\n")

for i in range(len(data)):
    input_data = data[i].reshape(1, 2)
    predicted_label = model.predict(input_data)[0][0].round()
    print(f"Input: {data[i]}, Predicted Output: {predicted_label}")

Training completed. Evaluating the model...

1/1 [==============================] - 0s 70ms/step
Input: [0 0], Predicted Output: 1.0
1/1 [==============================] - 0s 23ms/step
Input: [0 1], Predicted Output: 1.0
1/1 [==============================] - 0s 22ms/step
Input: [1 0], Predicted Output: 0.0
1/1 [==============================] - 0s 21ms/step
Input: [1 1], Predicted Output: 0.0


Tow_continues_variable_features_and_one_target_column_using_Keras_Neural_Netwrok

import library

In [29]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

# Load the dataset from a CSV file

In [30]:
data = {
    'Travel': [1.2, 2.1, 3.5, 4.0, 5.8],
    'Manufucturing': [0.5, 1.1, 2.6, 3.2, 4.9],
    'Proft_or_Loss': [0, 1, 0, 1, 0]
}

In [31]:
data

{'Travel': [1.2, 2.1, 3.5, 4.0, 5.8],
 'Manufucturing': [0.5, 1.1, 2.6, 3.2, 4.9],
 'Proft_or_Loss': [0, 1, 0, 1, 0]}

In [32]:
type(data)

dict

In [33]:
df=pd.DataFrame(data)

In [34]:
df

Travel  Manufucturing  Proft_or_Loss
0     1.2            0.5              0
1     2.1            1.1              1
2     3.5            2.6              0
3     4.0            3.2              1
4     5.8            4.9              0

In [35]:
type(df)

pandas.core.frame.DataFrame

# Split the dataset into training and testing sets

In [36]:
train_df, test_df = train_test_split(df, test_size=0.2)

In [37]:
train_df

Travel  Manufucturing  Proft_or_Loss
0     1.2            0.5              0
1     2.1            1.1              1
3     4.0            3.2              1
2     3.5            2.6              0

In [38]:
test_df

Travel  Manufucturing  Proft_or_Loss
4     5.8            4.9              0

# Prepare the input features and target labels

In [39]:
train_features = train_df[['Travel', 'Manufucturing']].values
train_labels = train_df['Proft_or_Loss'].values
test_features = test_df[['Travel', 'Manufucturing']].values
test_labels = test_df['Proft_or_Loss'].values

# Create the neural network model

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model

In [40]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

# Train the model

In [41]:
model.fit(train_features, train_labels, epochs=10, batch_size=1, verbose=1)

Epoch 1/10
4/4 [==============================] - 1s 5ms/step - loss: 0.6961 - accuracy: 0.5000
Epoch 2/10
4/4 [==============================] - 0s 7ms/step - loss: 0.6957 - accuracy: 0.5000
Epoch 3/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6957 - accuracy: 0.5000
Epoch 4/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6957 - accuracy: 0.5000
Epoch 5/10
4/4 [==============================] - 0s 6ms/step - loss: 0.6956 - accuracy: 0.5000
Epoch 6/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6956 - accuracy: 0.5000
Epoch 7/10
4/4 [==============================] - 0s 6ms/step - loss: 0.6956 - accuracy: 0.5000
Epoch 8/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6956 - accuracy: 0.5000
Epoch 9/10
4/4 [==============================] - 0s 7ms/step - loss: 0.6955 - accuracy: 0.5000
Epoch 10/10
4/4 [==============================] - 0s 7ms/step - loss: 0.6955 - accuracy: 0.5000


In [42]:
model.fit(train_features, train_labels, epochs=10, batch_size=2, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 10ms/step - loss: 0.6955 - accuracy: 0.5000
Epoch 2/10
2/2 [==============================] - 0s 9ms/step - loss: 0.6955 - accuracy: 0.5000
Epoch 3/10
2/2 [==============================] - 0s 9ms/step - loss: 0.6956 - accuracy: 0.5000
Epoch 4/10
2/2 [==============================] - 0s 8ms/step - loss: 0.6954 - accuracy: 0.5000
Epoch 5/10
2/2 [==============================] - 0s 9ms/step - loss: 0.6954 - accuracy: 0.5000
Epoch 6/10
2/2 [==============================] - 0s 9ms/step - loss: 0.6955 - accuracy: 0.5000
Epoch 7/10
2/2 [==============================] - 0s 9ms/step - loss: 0.6955 - accuracy: 0.5000
Epoch 8/10
2/2 [==============================] - 0s 8ms/step - loss: 0.6954 - accuracy: 0.5000
Epoch 9/10
2/2 [==============================] - 0s 8ms/step - loss: 0.6954 - accuracy: 0.5000
Epoch 10/10
2/2 [==============================] - 0s 9ms/step - loss: 0.6954 - accuracy: 0.5000


# Evaluate the model on the testing set

In [43]:
loss, accuracy = model.evaluate(test_features, test_labels, verbose=0)
print(f'Test loss: {loss:.4f}')
print(f'Test accuracy: {accuracy:.4f}')

Test loss: 0.6668
Test accuracy: 1.0000


# Make predictions on new data

In [44]:
new_data = {
    'Travel': [3.2, 5.1, 2.7],
    'Manufucturing': [1.8, 2.5, 4.0]
}

# 	Proft_or_Loss

In [45]:
new_df = pd.DataFrame(new_data)

In [46]:
predictions = model.predict(new_df.values)

1/1 [==============================] - 0s 54ms/step


In [47]:
print('Predictions:')
print(predictions)

Predictions:
[[0.48834506]
 [0.48558313]
 [0.5004507 ]]


In [48]:
# Make predictions
predictions = model.predict(new_df.values)
rounded_predictions = np.round(predictions)
print(rounded_predictions)


# new_data = {
#     'Travel': [3.2, 5.1, 2.7],
#     'Manufucturing': [1.8, 2.5, 4.0]
# }

1/1 [==============================] - 0s 31ms/step
[[0.]
 [0.]
 [1.]]
