# SciPy in Python

## 1. Basic Polynomial 

In [2]:
from numpy import poly1d
p=poly1d([3,6,9])
print(p)

   2
3 x + 6 x + 9


In [4]:
print(p)

   2
3 x + 6 x + 9


In [5]:
print(p*p)

   4      3      2
9 x + 36 x + 90 x + 108 x + 81


In [7]:
p

poly1d([3, 6, 9])

In [6]:
print("p(2)= ",p(2))

p(2)=  33


In [9]:
print("p(2) and p(3)= ",p([2,3]))

p(2) and p(3)=  [33 54]


In [10]:
# roots of p
p.r

array([-1.+1.41421356j, -1.-1.41421356j])

In [11]:
# Coefiicients of p
p

poly1d([3, 6, 9])

In [15]:
from numpy import poly1d
p=poly1d([3,6,9])

print("With respect to Velocity")
print(p)
p1=poly1d([3,6,9],variable='t')
print()
print("With respect to Time")
print(p1)

With respect to Velocity
   2
3 x + 6 x + 9

With respect to Time
   2
3 t + 6 t + 9


In [20]:
from numpy import poly1d
p=poly1d([3,6,9])

print("With respect to Accelearte")
p1=poly1d([3,6,9],variable='a')
print(p1)
p2=poly1d([3,6,9],variable='t')
print('-'*12)
print()
print('-'*12)
print()
print("With respect to Time")
print(p2)

With respect to Accelearte
   2
3 a + 6 a + 9
------------

------------

With respect to Time
   2
3 t + 6 t + 9


## 2. Special Function 

In [21]:
import scipy.special 
import numpy as np
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Cube Root
scipy.special.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [23]:
# Exponent of 10 (exp10())
x=3
scipy.special.exp10(x)

1000.0

In [25]:
# Exponent of 2 (exp2())
x=3
scipy.special.exp2(x)

8.0

In [26]:
# Degree of Radian (radian(d,m,s))
# Convert from degrees to radians. 
# Returns the angle given in (d)egrees, (m)inutes, and (s)econds in radian
d=30
m=10
s=50
scipy.special.radian(d,m,s)

0.5267500645255109

In [27]:
# Permutation
scipy.special.perm(5,2)   # 5P2=20

20.0

In [28]:
# Combination
scipy.special.comb(5,2)   # 5C2=20

10.0

## 3. Integration 

In [29]:
import scipy.integrate
f=lambda x:x**2
f(3)

9

In [30]:
f(6)

36

In [31]:
f=lambda x,y:x*y
f(3,5)

15

In [33]:
f=lambda x:x**2
i=scipy.integrate.quad(f,1,2)
i

(2.3333333333333335, 2.590520390792032e-14)

## 4. Matrix Manipulations 

In [35]:
A=np.array([[1,2,3],[5,6,7],[9,3,5]])
A

array([[1, 2, 3],
       [5, 6, 7],
       [9, 3, 5]])

In [39]:
from scipy import linalg

In [40]:
linalg.inv(A)

array([[-0.28125,  0.03125,  0.125  ],
       [-1.1875 ,  0.6875 , -0.25   ],
       [ 1.21875, -0.46875,  0.125  ]])

In [48]:
# Cross Check A*inv(A)=I
I=A.dot(linalg.inv(A))
# print(I)
print(np.around(I))

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]
